export const portfolioItems = [
  {
    id: 1,
    title: "Classic Lash Set",
    image: "/assets/images/lash.jpg",
    category: "lashes",
    description: "Beautiful classic lash application",
    tags: ["classic", "lashes", "professional"],
  },
  {
    id: 2,
    title: "Ombre Powder Brow",
    image: "/assets/images/brows.jpg",
    category: "brows",
    description: "Stunning ombre powder brow design",
    tags: ["ombre", "brows", "powder"],
  },
  {
    id: 3,
    title: "Luxury Spa Treatment",
    image: "/assets/images/Luxury spa body oil.png",
    category: "spa",
    description: "Relaxing full body spa experience",
    tags: ["spa", "luxury", "relaxation"],
  },
  {
    id: 4,
    title: "Custom Tattoo Design",
    image: "/assets/images/tatoos.jpg",
    category: "tattoo",
    description: "Beautiful custom tattoo artwork",
    tags: ["tattoo", "custom", "art"],
  },
  {
    id: 5,
    title: "Volume Lash Set",
    image: "/assets/images/lash.jpg",
    category: "lashes",
    description: "Dramatic volume lash extensions",
    tags: ["volume", "lashes", "dramatic"],
  },
  {
    id: 6,
    title: "Microblading Brows",
    image: "/assets/images/brows.jpg",
    category: "brows",
    description: "Natural looking microbladed eyebrows",
    tags: ["microblading", "brows", "natural"],
  },
  {
    id: 7,
    title: "Full Body Massage",
    image: "/assets/images/Luxury spa body oil.png",
    category: "spa",
    description: "Therapeutic full body massage",
    tags: ["massage", "spa", "therapeutic"],
  },
  {
    id: 8,
    title: "Sleeve Tattoo",
    image: "/assets/images/tatoos.jpg",
    category: "tattoo",
    description: "Intricate sleeve tattoo design",
    tags: ["sleeve", "tattoo", "intricate"],
  },
];

export const categories = [
  { id: "all", name: "All Services" },
  { id: "lashes", name: "Lashes" },
  { id: "brows", name: "Brows" },
  { id: "spa", name: "Spa" },
  { id: "tattoo", name: "Tattoo" },
];

export const products = [
  {
    id: 1,
    name: "Easy Lash Fan Tray",
    price: 45.99,
    image: "/assets/images/Easy lash fan tray.png",
    category: "lashes",
    description: "Professional lash extension fan tray",
    inStock: true,
  },
  {
    id: 2,
    name: "Lash Glue (5ml)",
    price: 12.99,
    image: "/assets/images/lash glue five.png",
    category: "lashes",
    description: "Premium quality lash adhesive",
    inStock: true,
  },
  {
    id: 3,
    name: "Lash Glue (10ml)",
    price: 19.99,
    image: "/assets/images/lash glue ten.png",
    category: "lashes",
    description: "Large size lash adhesive",
    inStock: true,
  },
  {
    id: 4,
    name: "Brow Mapping Pen",
    price: 8.99,
    image: "/assets/images/brow mapping pen.png",
    category: "brows",
    description: "Precision brow mapping tool",
    inStock: true,
  },
  {
    id: 5,
    name: "Brow Sealant",
    price: 14.99,
    image: "/assets/images/brow sealant.png",
    category: "brows",
    description: "Protective brow sealant",
    inStock: true,
  },
  {
    id: 6,
    name: "Luxury Spa Body Oil",
    price: 29.99,
    image: "/assets/images/Luxury spa body oil.png",
    category: "spa",
    description: "Premium relaxing body oil",
    inStock: true,
  },
  {
    id: 7,
    name: "Clay Detox Mask",
    price: 24.99,
    image: "/assets/images/clay detox.png",
    category: "spa",
    description: "Detoxifying clay mask",
    inStock: true,
  },
  {
    id: 8,
    name: "Spa Towel Set",
    price: 34.99,
    image: "/assets/images/spa towel set.png",
    category: "spa",
    description: "Luxury spa towel set (3 pieces)",
    inStock: true,
  },
  {
    id: 9,
    name: "Lash Sealant",
    price: 16.99,
    image: "/assets/images/lash sealant.png",
    category: "lashes",
    description: "Professional lash sealant",
    inStock: false,
  },
  {
    id: 10,
    name: "Lash Wash Brush",
    price: 9.99,
    image: "/assets/images/lash wash brush.png",
    category: "lashes",
    description: "Gentle lash cleaning brush",
    inStock: true,
  },
];
